---
title: "Thompson_Hendley_hw5"
author: "Bradley Thompson & John Hendley"
date: "11/18/2020"
output: pdf_document
---

```{r setup, echo=FALSE, results=TRUE}
knitr::opts_chunk$set(error=TRUE, dev="cairo_pdf")
library(tidyverse)
library(purrr)
```

## Number 1
``` {r Num1}
# Takes the basic color palette and spreads it into 50 colors
expand_palette <- function(n, colors) {
  spread <- colorRampPalette(colors)
  spread(n)
}

colors <- brewer.pal(9, "Spectral")
more_colors <- expand_palette(50, colors)
show_col(more_colors, labels = FALSE)
```


```{r, echo = FALSE}
#dot
dot <- function(x, y){
  if (length(x) != length(y)) stop("vectors `x` and `y` are not of the same length.")
  # loop over the vector, accumulating the inner product
  out <- 0 
  for (i in seq_along(x)) out <- out + x[i]*y[i]# return inner product
  out
}

#norm 
norm <- function(x) sqrt(dot(x, x))

#normalize
normalize <- function(x) x / norm(x)

#is zero
is.zero <- function(x) norm(x) < sqrt(.Machine$double.eps)

#projection
# project_onto <- function(y,x){
#   projection <- c(1:length(x))
#   if(is.zero(x)){
#     for(i in 1:length(x)){
#       projection[i] <- 0
#     }
#   }
#   else{
#     projection <- dot(y,x)/dot(x,x)*x
#   }
#   projection
# }
project_onto <- function(y, x, normalized_x = FALSE){
  stopifnot(length(x) == length(y))
  if (is.zero(x)) return(rep(0, length(x)))
  if (normalized_x) dot(y, x) * x else dot(y, x) / dot(x, x) * x
}
#discard zero cols
discard_zero_cols <- function(M) M[,!apply(M, 2, is.zero)]


#gs
gs <- function(A){
  # initialize basis matrix
  e <- matrix(0, nrow = nrow(A), ncol = ncol(A))
  e[,1L] <- normalize(A[,1L])
  # orthogonalize and normalize column by column
  for (j in 2L:ncol(A)){
    e_tilde <- A[,j]
    # subtract parallel components
    for (k in 1L:(j-1L)){
      e_tilde <- e_tilde - project_onto(e_tilde, e[,k]
                                        , normalized_x = TRUE
                                        )
      }
    # normalize
    if (norm(e_tilde) < sqrt(.Machine$double.eps)){
      e[,j] <- rep(0, nrow(A))
      }else{
        e[,j] <- normalize(e_tilde)}
    }# end for loop over columns
  # return
  discard_zero_cols(e)
}
```

## Number 2
```{r}
mgs <- function(A){
  #make skipping vector
  skip_vector <- vector(mode = "integer", length = ncol(A))
  for(i in 1:ncol(A)){
    #normalize
    if(!is.zero(A[, i])){
      A[, i] <- normalize(A[, i])
    }
    #subtract projections
    if(i != ncol(A)){
      for(j in (i + 1):ncol(A)){
        #check if in skip vector
        if(j %in% skip_vector){
          break()
        } else {
          A[, j] <- A[, j] - project_onto(A[, j], A[, i])
          if(is.zero(A[, j])){
            skip_vector[j] <- j
          }
        }
      }
    }
  }
  discard_zero_cols(A)
}

#testing
A <- matrix(c(1, 6, 19, 2, 1, 2,  7, 3, 5, 6, 23, 2), nrow = 3, byrow = TRUE)
gs(A)
mgs(A)
```

## Number 3
```{r}
#array to tibble 
array_to_tibble <- function(a){
  df <- a %>% 
  dim() %>% 
  map(~ 1:.x) %>% 
  expand.grid() %>% 
  as_tibble()
names(df) <- paste0("i", 1:length(dim(a)))
df$value <- as.vector(a)
df
}

#testing
mat <- matrix(1:6, nrow = 2)
array_to_tibble(mat)
a <- array(1:24, dim = c(2, 4, 3))
array_to_tibble(a)
```

## Number 4
```{r Num4}
library(tibble)

# The spy function takes as arguments the generated matrix along with the
# number of rows and columns (n) of the square matrix.
spy <- function(mat, n) {
  non_zero_row = c()
  non_zero_col = c()

# Searches through matrix and notes the indices of non-zero elements
  for (i in 1:n) {
    for (j in 1:n) {
      if (mat[i, j] != 0) {
        non_zero_row = c(non_zero_row, i)
        non_zero_col = c(non_zero_col, j)
      }
    }
  }
  # Due to the way R orients the coordinate system, this code
  # calibrates things to output in the desired way
  x_plot <- non_zero_col # col is distance from left
  y_plot <- n - non_zero_row # row is distance from top

  tibble(x = x_plot, y = y_plot)
}

n <-  50
mat <- matrix(0L, nrow = n, ncol = n)
set.seed(2L)
mat[sample(n^2, n)] <- rpois(n, 5)

# Calls the spy function to create the tibble to be plotted
df <- spy(mat, n)

# Uncomment the next two lines and comment all the above to test
# the base case.
# n <- 10
# df <- tibble(x = 1:10, y = 10:1)

ggplot(df, aes(x, y)) +
  # Creats the black box around the plot
  geom_rect(aes(xmin = 0.5, xmax = n + 0.5, 
            ymin = 0.5, ymax = n + 0.5), 
            fill = "white", color = "black", size = 0.2) +
  geom_tile(fill = "black") +
  scale_x_continuous(name = NULL, breaks = NULL, minor_breaks = NULL) +
  scale_y_continuous(name = NULL, breaks = NULL, minor_breaks = NULL) +
  coord_equal()
```

